In [1]:
from simulated_df import *

# Create simulated dataset

df = create_simulated_df(n_samp=500)

In [2]:
# Show first 10 items in dataframe, ordered by date

df.head(10)

,people,topics,category,status,datatypes,database,difficulty
date,,,,,,,
2011_04,franco_alex,data_science,presentation,poster,behavioral,nki,intermediate
2011_04,klein_arno,machine_learning,research,proceeding,eye_tracking,fcp,NA
2011_04,NA,medicine,cmi_staff,proceeding,fmri,nki,beginner
2011_04,NA,machine_learning,NA,publication,eeg,hbn,beginner
2011_04,kramer_eliza,data_science,research,NA,audio,nki,beginner
2011_04,xu_ting,NA,cmi_staff,NA,eeg,hbn,intermediate
2011_04,NA,coding,NA,poster,eye_tracking,fcp,beginner
2011_04,klein_arno,grad_school,presentation,in_progress,NA,nki,intermediate
2011_04,gregory_camille,neuroscience,resource,proceeding,actigraphy,fcp,advanced
2011_04,franco_alex,coding,cmi_staff,proceeding,NA,hbn,NA

In [3]:
# This is how the data in a CSV file would normally be loaded:

# df = pd.from_csv('/path/to/data/file.csv').sort_values('date')

In [5]:
# Filter by topic

filters, filtered_df = search_topic(df)

Here's a list of topics:

TypeError: 'module' object is not callable

In [44]:
# Show first 10 items in updated dataframe, ordered by date

print(str('\nThere are {} results for your search term: {}.').
      format(filtered_df.shape[0], filters))

filtered_df.head(10)

There are 65 results for your search term: data_science.

,presenters,topics,category,status,datatypes,database,difficulty
date,,,,,,,
2011_04,alexander_lindsay,data_science,presentation,publication,eeg,NA,NA
2011_04,kramer_eliza,data_science,research,NA,eeg,nki,advanced
2011_04,camacho_nicolas,data_science,research,publication,eye_tracking,adhd200,intermediate
2011_04,kramer_eliza,data_science,NA,publication,NA,hbn,intermediate
2011_04,septimus_batya,data_science,presentation,proceeding,genetic,nki,intermediate
2011_04,koo_bonhwang,data_science,research,NA,fmri,NA,advanced
2011_04,septimus_batya,data_science,research,poster,eye_tracking,nki,NA
2011_04,xu_ting,data_science,research,proceeding,eye_tracking,adhd200,beginner
2011_04,alexander_lindsay,data_science,resource,publication,eeg,hbn,advanced
2011_04,koo_bonhwang,data_science,resource,NA,actigraphy,fcp,advanced

In [56]:
# Filter by datatype

filters, filtered_df = search_datatype(df)

What datatypes are you interested in?: fmri

Dataframe updated.

In [57]:
# Show first 10 items in updated dataframe, ordered by date

print(str('\nThere are {} results for your search term: {}.').
      format(filtered_df.shape[0], filters))

filtered_df.head(10)

There are 59 results for your search term: fmri.

,presenters,topics,category,status,datatypes,database,difficulty
date,,,,,,,
2011_04,alexander_lindsay,psychology,NA,poster,fmri,adhd200,advanced
2011_04,camacho_nicolas,psychology,presentation,poster,fmri,nki,advanced
2011_04,septimus_batya,psychopharm,NA,in_progress,fmri,adhd200,advanced
2011_04,septimus_batya,machine_learning,NA,publication,fmri,fcp,intermediate
2011_04,kramer_eliza,psychopharm,NA,proceeding,fmri,fcp,NA
2011_04,koo_bonhwang,data_science,research,NA,fmri,NA,advanced
2011_04,NA,psychopharm,NA,proceeding,fmri,fcp,intermediate
2011_04,gregory_camille,machine_learning,NA,in_progress,fmri,nki,beginner
2011_04,gregory_camille,medicine,NA,NA,fmri,fcp,intermediate
2011_04,franco_alex,data_science,resource,publication,fmri,fcp,beginner

In [3]:
# Filter by multiple features

filters, filtered_df = search_multiple(df, topics=True, category=False, status=False,
                                       datatypes=False, database=True, difficulty=False)

Here's a list of topics:
['data_science',
 'machine_learning',
 'medicine',
 'NA',
 'coding',
 'grad_school',
 'neuroscience',
 'psychology',
 'psychopharm']
What topic are you interested in?: grad_school

Dataframe updated.
Here's a list of databases
['nki', 'NA', 'hbn', 'fcp', 'adhd200']
What datatypes are you interested in?: hbn

Dataframe updated.

In [4]:
# Show first 10 items in updated dataframe, ordered by date

print(str('\nThere are {} results for your search terms: {}.').
      format(filtered_df.shape[0], filters))

filtered_df.head(10)

There are 7 results for your search terms: ['grad_school', 'hbn'].

,people,topics,category,status,datatypes,database,difficulty
date,,,,,,,
2011_04,koo_bonhwang,grad_school,NA,proceeding,fmri,hbn,beginner
2013_09,camacho_nicolas,grad_school,research,publication,fmri,hbn,beginner
2013_09,gregory_camille,grad_school,resource,in_progress,eye_tracking,hbn,NA
2013_09,gregory_camille,grad_school,NA,publication,NA,hbn,advanced
2013_09,alexander_lindsay,grad_school,presentation,in_progress,eye_tracking,hbn,advanced
2017_12,xu_ting,grad_school,resource,proceeding,NA,hbn,advanced
2018_04,alexander_lindsay,grad_school,NA,poster,genetic,hbn,NA